### ISSUE TITLE
Add Amcrest Hex 960P Wi-Fi video camera

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#104]
Let's wait to implement until we have a sample (or customer) to test.

This may just need verification of OUI since the RTSP path looks similar to other Amcrest/Dahua:
https://amcrest.com/new-products/amcrest-hex-960p-wifi-video-security-ip-camera-pt.html

https://s3.amazonaws.com/amcrest-files/AMCREST_HTTP_API_SDK_V2.10.pdf
example:
```
rtsp://admin:admin@10.7.6.67:554/cam/realmonitor?channel=1&subtype=1 
```
OUI in user manual screenshot is Dahua:
```
90:02:A9
```

**Comment by jhallard** [comment]
did this info ever get confirmed?

**Comment by jhallard** [comment]
anyway this seems to be all of the same info as for the Amcrest IP2M-841 camera entry that we already have in `cameras/paths.csv`, with the stream hard-coded to 1. The OUI is even the same so we would be able to identify this camera today. I'll change the name of the camera entry to include both the IP2M-841 and the 'Hex 960P' names.
