### ISSUE TITLE
Add Foscam R2 (44:2C:05)

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#117]
OUI:
`44:2C:05` AMPAK Technology, Inc.

RTSP Path:
`/video{{stream}}`

streams are:
`Main;Sub`

So that the effective path is either:
`/videoMain`
or
`/videoSub`

Default Port is `554` but may be `88` or others set by user.

manual:
http://www.foscam.com/Uploads/manual/20170519/R2%20R4%20User%20Manual%20V2.1.rar

**Comment by jcmaslan** [comment]
@jhallard we already have an [entry from R2](https://github.com/CamioCam/rtsp/blob/master/cameras/paths.csv#L6), so we just need to:
1. add this new OUI
2. parameterize stream for Main and Sub
3. leave the default port as 88 for now

**Comment by jhallard** [comment]
this was done (https://github.com/CamioCam/rtsp/pull/102) so closing
