### ISSUE TITLE
Add IONodes ION-E100 Encoder

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#125]
User manual:
http://www.ionodes.com/main/uploads/manuals/ION-E100_UserManual.pdf

RTSP URL is like:
```
rtsp://<DEVICE_IP>:<Port>/<SourceType>_<Instance> :<boardId>/<EncoderName>/<Type>.stm
```

e.g. requesting a video stream from the primary H.264 encoder of video input #2:
```
rtsp://10.1.1.2:554/videoinput_2/h264_1/media.stm
```
API docs are in:
https://drive.google.com/drive/folders/0B5F28cfjJYaZc2ZlZWYyOVJQRVE?usp=sharing

**Comment by jhallard** [comment]
so how should this all translate to an RTSP URL?

`rtsp://{{username}}:{{password}}@{{ip_address}}:{{port}}/videoinput_{{channel}}/h264_{{stream}}/media.stm`

? where channel and stream can both be {1, 2}? @jcmaslan
