### ISSUE TITLE
Add Reolink RLC-423S camera support

### ISSUE THREAD

**Issue by jhallard** [CamioCam/rtsp#162]
OUI: EC71DB

rtsp path: /h264Preview_01_main

(https://www.ispyconnect.com/man.aspx?n=reo-link)

**Comment by jcmaslan** [comment]
Just adding additional reference links:
https://support.reolink.com/hc/en-us/articles/360007010473-How-to-Live-View-Reolink-Cameras-via-VLC-Media-Player

The RTSP URL should be:

Main Stream: rtsp://admin:password@ip_address:554//h264Preview_01_main

Sub Stream: rtsp://admin:password@ip_address:554//h264Preview_01_sub

For example, if your device IP address is 192.168.0.110 and the password is 111111, then your RTSP URL should be:

Main Stream: rtsp://admin:111111@192.168.0.110:554//h264Preview_01_main

Sub Stream:  rtsp://admin:111111@192.168.0.110:554//h264Preview_01_sub
