### ISSUE TITLE
Add TVT DVR (8-channel)

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#170]
http://en.tvt.net.cn/
5MP 8CH Coaxal DVR

OUI: 00:18:AE

rtsp://{{username}}:{{password}}@{{ip_address}}:554/?chID={{channel}&streamType={{stream}}&linkType=tcp

stream is "main" (not sure of others)
channel is 1,2,3,4,5,6,7,8

**Comment by premvenus** [comment]
perfect its working for me i am really appreciate you effort
