### ISSUE TITLE
add ADT A-ADT4H2S

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#177]
example after enabling RTSP:
rtsp://admin:DVRPASSWORD@10.0.0.123:554/trackID=1

The OUI *might* be:
00:03:22

4 channels 1,2,3,4, so:
rtsp://{{username}}:{{password}}@{{ip_address}}:{{port}}/trackID={{channel}}

**Comment by casebeer** [comment]
Note that when I start up the Box VM, it auto-detected my ADT DVR as a Revo device, which has the same OUI and RTSP URL pattern in your CSV. 

Must be the same OEM, so I'm not sure a separate config for the ADT device is needed. I do see too many channels in the Camio UI, which makes the Box settings page cluttered. 

I believe this is the [device spec sheet](http://www.adt-matrix.com/downloads/spec-sheets/A-ADT4HS_MNI2011-02.pdf).

[This](http://www.adt-matrix.com/downloads/manuals/DRC4HS_TISv1.3_opt.pdf) seems to be the manual, even though it has the wrong model number. The screenshots etc. seem to match at first glance, and the RTSP URL is correct except `trackID` (correct, working in practice) is misspelled `track ID` (as documented in that PDF).

**Comment by casebeer** [comment]
Confirmed via the Camio Box settings UI that the MAC for the NVR is 000322xxxxxx.
