### ISSUE TITLE
add new field unsupported_rtsp_transports

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#21]
Since some cameras do not support tcp as transport for rtsp, add an _optional_ field that enumerates the unsupported transports as semi-colon separated list in the format specified by https://www.ietf.org/rfc/rfc2326.txt. Perhaps `unsupported_rtsp_transports`.

**Comment by jhallard** [comment]
I was unable to figure out the syntax for specifying multiple transport types (ie `-rtsp_transport tcp,udp` or `-rtsp_transport tcp udp`), but I did find the following option that I think does what we need very simply.

`-rtsp_flags prefer_tcp`. I've added this to the code on my branch and am testing now.

I'm getting my info off of this page for reference : https://www.ffmpeg.org/ffmpeg-protocols.html

**Comment by jcmaslan** [comment]
much better approach. closing this issue since it's now unneeded in this public repo.
