### ISSUE TITLE
OVISS ProS NVR

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#211]
OVISS ProS NVR

rtsp://{{ip_address}}:{{port}}/unicast/c{{channel}}-n/s{{stream}}/live

`channel` is `1;2;3;4;5;6;7;8`
`stream` is `0;1`

Stream 0 is `main stream`
Stream 1 is `sub stream`

Example:
rtsp://10.1.10.51:8554/unicast/c1-n/s0/live  

Getting OUI...

**Comment by jhallard** [comment]
@jcmaslan let me know if you're able to get the OUI for this one and I'll get it added, I have a branch ready.

**Comment by jcmaslan** [comment]
Unfortunately it is the same oui as the camera. But we handle that Ok.

**Comment by jhallard** [comment]
I must be missing something, I don't see any OVISS camera entries in the paths.csv file. What is the camera OUI you're referring to?

**Comment by jcmaslan** [comment]
https://github.com/CamioCam/rtsp/issues/210

**Comment by jhallard** [comment]
thanks! I missed that issue
