### ISSUE TITLE
Hanwha multi-sensor

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#229]
Example that shows sensor 1:

rtsp://username:password@10.0.0.153:554/1/profile2/media.smp

```
rtsp://{{username}}:{{password}}@{{ip_address}}:{{port}}/{{channel}}/profile{{stream}}/media.smp
```

`channels` are `0;1;2;3`
(sensors 0-3)

`streams` are only `2` for now (as H.264)

OUI is `00:09:18`

See doc at:
https://support.hanwhasecurity.com/hc/en-us/articles/236372028-Camera-RTSP-URL

please fix this along with issue #196 to make `2` the default.

**Comment by jhallard** [comment]
default username and password? admin:admin?
