### ISSUE TITLE
Add config to disable illegal login lock for Hikvision

### ISSUE THREAD

**Issue by jhallard** [CamioCam/rtsp#34]
This option seems to be on by default on hikvision cameras 

![image](https://cloud.githubusercontent.com/assets/7551586/18571993/d6defd6e-7b6b-11e6-83c6-245a43904977.png)

If it is true, we get locked out after a certain amount of failed attempts. Since we are trying to connect to cameras in a tight-loop, a user who enters wrong credentials might end up getting locked out quickly, and I'm not sure how long the lockout persists for.

We should analyze the network traffic when checking/unchecking this option then add a command to unset this option for hikvision cameras.

**Comment by jcmaslan** [comment]
@jhallard better to implement the fast backoff that avoids retry until the user has changed username or password.

**Comment by jhallard** [comment]
This is implemented - I might need to make the back off a bit more aggressive though but the back off logic already exists on Camio Box.

**Comment by jcmaslan** [comment]
@jhallard you detect changes in username and password as a pre-condition to retry? That's what I meant.

**Comment by jhallard** [comment]
We use 'options changed' for that specific camera, we don't check that it's necessarily the username and/or password that's changed.
