### ISSUE TITLE
Add Zavio B8520 motorized bullet

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#49]
RTSP verified using this manual:
http://www.zavio.com/downloads/product/90/User%20Manual_%205MP%20B8520%20motorized%20bullet%20_1028.pdf

Which confirmed:
RTSP Configuration: This option allows you to set up the URL for each profile and define whether or not you want to enable or disable authentication. By default, the video URL and profile number are related, e.g., profilex = video.prox, but you change it any way you like. Based on the default URLs, access to the RTSP streams would be done like this: rtsp://camera_address:554/video.pro1 rtsp://camera_address:554/video.pro2 rtsp://camera_address:554/video.pro3 rtsp://camera_address:554/video.pro4 If authentication is enabled, the URLs will change as follows: rtsp://username:password@camera_address:554/video.pro1 [...] rtsp://username:password@camera_address:554/video.pro4

**Comment by jhallard** [comment]
I'll put the 8520 and 8220 in the same item. The OUI I found for Zavio is  00:1B:FE, but I've never actually used one of them and confirmed this as correct. I wasn't able to find any information in either manual about default credentials either.

**Comment by jhallard** [comment]
I don't have information on how the default profiles work, i.e. which are higher quality and which are lower. Should I just name them 'one, two, three, four'?

**Comment by jcmaslan** [comment]
Yes, just make template like:

```
Profile {{stream}}
```

Manual says that only profile 1 and profile 3 can support HD, so let's list only:

```
1;3
```

<img width="355" alt="screen shot 2016-11-05 at 8 32 40 am" src="https://cloud.githubusercontent.com/assets/915853/20031306/84368c96-a332-11e6-94ad-85e197f64476.png">

**Comment by jcmaslan** [comment]
On second thought, we shouldn't limit use of profiles, so go ahead and include them all @jhallard 

```
1;2;3;4
```

**Comment by jhallard** [comment]
Done, stream names are now 'Profile {{stream}}'
