### ISSUE TITLE
Add dbell doorbell camera

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#50]
username: admin
default password: admin
default port: 554

rtsp url:
rtsp://{{username}}:{{password}}@{{ip_address}}:{{port}}/av0_0

I'm not sure whether it should be:
/av{{channel}}_{{stream}} so we'll wait until we receive a unit/manual to investigate - for now, just hard-code the av0_0.

**Comment by jhallard** [comment]
do we have an OUI? I couldn't find one with my Googlefu.

**Comment by jcmaslan** [comment]
no, you can wait until we get one to try out and identify OUI.
