### ISSUE TITLE
ACTi A82 Dome

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#51]
MAC Address OUI:
`00:0F:7C`

RTSP:
rtsp://{{username}}:{{password}}@{{ip_address}}:7070/track{{stream}}

streams:
1;2;3

default stream:
1

stream name template:
Stream {{stream}}

user manual:
http://www2.acti.com/getfile/KnowledgeBase_UploadFile/Third_Party_or_Open_Source_Software_Integration_20100402_006.pdf

**Comment by jcmaslan** [comment]
As long as you're deploying @jhallard can you include this too? It's 100% confirmed with help from EOS.

**Comment by jhallard** [comment]
done with 7e157912d5ef8084a54578863fa492e80675d26e, there isn't any default username/password information right?

**Comment by jcmaslan** [comment]
LGTM.
