### ISSUE TITLE
Add doorbird doorbell camera

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#53]
RTSP:
```
rtsp://{{username}}:{{password}}@{{ip_address}}:{{port}}/mpeg/media.amp
```
default RTSP port is 554. RTSP-over-HTTP is port 8557.

documentation at http://www.doorbird.com/downloads/api_lan.pdf?rev=0.13.

**Comment by jhallard** [comment]
Do we have an OUI for these guys? Can't seem to find one online..

**Comment by jhallard** [comment]
Also can't find information on any default credentials for the device.

**Comment by jhallard** [comment]
initial draft here: d68c47a

it's ready except I just put admin as default username for now.
