### ISSUE TITLE
Add Vivotek camera information

### ISSUE THREAD

**Issue by jhallard** [CamioCam/rtsp#72]
I'm waiting on a customer to get back with this information, if they can't / don't know it then I'll look it up myself.

OUI: `0002D1`

**Comment by jcmaslan** [comment]
For Vivotek CC8130 http://www.vivotek.com/cc8130/

http://download.vivotek.com/downloadfile/downloads/usersmanuals/cc8130manual_en.pdf

RTSP url is `rtsp://{{username}}:{{password}}@{{ip_address}}:{{port}}/{{stream}}.sdp`

default port is `554`

streams are `live;live2;liveany`
![screen shot 2016-12-15 at 12 47 52 pm](https://cloud.githubusercontent.com/assets/915853/21241788/301760c8-c2c6-11e6-8efd-f8cc48cb66c3.png)

default settings have no username or password protection @jhallard so you may have to modify the importer to accept none.

**Comment by jhallard** [comment]
Fixed by 2702c569d2b84f44656ae7183743dc8be416228f (put the wrong number in the commit, apologies).
