### ISSUE TITLE
Add 4K DAHUA hfw81200 camera

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#74]
OUI is `4C11BF`

RTSP Path is empty
RTSP Server is standard:
rtsp://{{username}}:{{password}}@{{ip_address}}:{{port}}

default port 554

couldn't find user manual, but add this link for now:
http://www1.dahuasecurity.com/products/ipc-hfw81200e-z-1159.html

**Comment by jhallard** [comment]
I'm seeing different sets of default credentials, should we pick one or just leave it empty?

http://www.cleancss.com/router-default/Dahua/IPC-HFW2100

**Comment by jcmaslan** [comment]
use admin admin
