### ISSUE TITLE
Add Luma NVR and Wirepath IP camera

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#77]
NVR manual:
https://www.snapav.com/wcsstore/ExtendedSitesCatalogAssetStore/attachments/documents/Surveillance/ManualsAndGuides/Luma-500%20Technical%20Reference%20Manual.pdf

Reference tech bulletin:
https://www.snapav.com/wcsstore/ExtendedSitesCatalogAssetStore/attachments/documents/Surveillance/ProtocolsAndDrivers/Streaming_Protocols_20160613.pdf

DVR's rtsp_url:
```
rtsp://{{username}}:{{password}}@{{ip_address}}:{{port}}{{channel}}/Streaming/channels/{{channel}}{{stream}}
```
NOTE: the unusual formation of the effective port as the concatenation of the "base port" and the channel, so we should treat `port` like `631` so that the effective port range will be like 63101–63108

channels are `1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16`
streams are `01;02` for `main stream;sub stream`
Example for channel 14 main stream: rtsp://admin:password@173.200.91.70:10554/Streaming/channels/1401
Example for channel 2 sub stream: rtsp://admin:password@173.200.91.70:10554/Streaming/channels/202

Wirepath IP Cameras (Not for Luma Recorders)
rtsp_url:
```
http://{{username}}:{{password}}@{{ip_address}}:{{port}}/GetData.cgi?CH={{channel}}&Codec=h264
```
channels seems to be single value of `1`
not sure about default `port`.

Example: http://127.0.0.1:8001/GetData.cgi?CH=1&Codec=h264

**Comment by jhallard** [comment]
do you have access to either of these so we can figure out the OUIS?

**Comment by jhallard** [comment]
Added the majority of what's needed with 34e0f62b1e6fbe9751e5d3130d59155ed91d8c4e but I still need the OUIs for both Wirepath and Luma to complete the entries, couldn't find this information through simple Google search.

**Comment by jcmaslan** [comment]
I've asked a user for help with MACs with:
`sudo arp-scan --interface=en0 --localnet`
and I'll add OUIs when he replies.

**Comment by jcmaslan** [comment]
At least for one customer, the NVR OUI is:
`00:0F:0D` Hunt Electronic Co., Ltd.

The camera is unfortunately the same (so we need the fix to retain multiple candidate paths):
`00:0F:0D`Hunt Electronic Co., Ltd.

But one of the other cameras uses a different OUI unique to Snap AV:
`D4:6A:91` Snap AV
