### ISSUE TITLE
Add UniFi NVR

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#81]
manual:
https://dl.ubnt.com/guides/unifivideo/UniFi_Video_UG.pdf

The RTSP URL doesn't follow a pattern, so it must be enabled and entered for each individual camera stream for HIGH, MEDIUM, or LOW:
![screen shot 2017-01-06 at 12 43 24 pm](https://cloud.githubusercontent.com/assets/915853/21732299/c3099efc-d40d-11e6-9555-7b168eecabff.png)

```
rtsp://{{username}}:{{password}}@{ip_address}}:{{port}}
```
So the user will have to enter the RTSP path manually like `/abc123xyz` after generating the RTSP URL using the UniFi NVR. There is no stream or channel in the template for that reason.

NVR's OUI is:
`D0:27:88` (from Hon Hai Precision Ind. Co.,Ltd.)

default port:
`554`

**Comment by jhallard** [comment]
Okay so to be clear, we set rtsp-server to: rtsp://{{username}}:{{password}}@{ip_address}}:{{port}}

and the rtsp-path will have to be hand-entered by the user after they generate a path on the NVR?

**Comment by jcmaslan** [comment]
correct. I've requested [testing help](https://www.reddit.com/r/Ubiquiti/comments/5mg5ro/testing_unifi_nvrs_rtsp_streams/), so standby...
