### ISSUE TITLE
Add Zmodo 4-channel NVR

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#83]
Don't implement this until the customer confirms RTSP URL accuracy.

This article isn't yet confirmed as accurate for the NVR:
http://kb.zmodo.com/index.php?solution_id=1308
The RTSP address of the main stream (720p) is:
rtsp://xxx.xxx.xxx.xxx:10554/tcp/av0_0
The RTSP address of the sub stream (VGA) is:
rtsp://xxx.xxx.xxx.xxx:10554/tcp/av0_1

so rtsp_url is:
```
rtsp://{{username}}:{{password}}@{{ip_address}}:{{port}}/tcp/av{{channel}}_{{stream}}
```
`channels` are:
0;1;2;3

`streams` are:
0;1

default username is:
`admin `

default password is:
`111111`

**Comment by jhallard** [comment]
I found this OUI for Zmodo: 045C06

Got it from here: http://www.adminsub.net/mac-address-finder/zmodo

I'll put it in as a place holder but we should have customer confirm.

**Comment by jhallard** [comment]
Added here: 4af6bc6, awaiting customers confirmation then I'll make the PR.
